trigger:
- 

pool:
  vmImage: 'ubuntu-latest'

variables:
  armConnection: 'arm-connection'
  resourceGroup: 'VisualStudioOnline-B7676031D19941C29CB021209999B63D'
  storageAccount: 'corvitterraformstate'
  container: 'tfstate'
  tfstateKey: 'terraform.tfstate'

stages:
- stage: Infra_Provisioning
  displayName: 'Stage 5: Terraform Infrastructure'
  # Only run this if we are NOT trying to destroy
  condition: and(succeeded(), ne(variables['Build.Reason'], 'Manual')) 
  jobs:
  - job: TerraformApply
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceArm: $(armConnection)
        backendAzureRmResourceGroupName: $(resourceGroup)
        backendAzureRmStorageAccountName: $(storageAccount)
        backendAzureRmContainerName: $(container)
        backendAzureRmKey: $(tfstateKey)

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceNameAzureRM: $(armConnection)
        commandOptions: '-auto-approve'

  
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceNameAzureRM: $(armConnection)
        commandOptions: '-auto-approve'
